### ISSUE TITLE
No option to delete source .zip file when an endpoint is removed

### ISSUE THREAD

**Issue by mjhilton** [Particular/NServiceBus.Host.AzureCloudService#13]
Related to https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/100

When a running endpoint's .zip source package is removed from blob storage, the endpoint is deprovisioned and the extracted endpoint files are removed, but the .zip file remains on disk. Over time, this will cause the Role Instance's LocalStorage to fill up and exceed the allowed quota, triggering a role recycle.

Add an option to remove the .zip source package as part of the deprovisioning process.

**Comment by SeanFeldman** [comment]
@mjhilton what was the size of your endpoint(s) zip and how big was LocalStorage?

**Comment by mjhilton** [comment]
@SeanFeldman we were running 11 different endpoints around 10mb each, and using numbered versioning of the zip files, so each time we upgraded the endpoints (very regularly due to this being part of a CI process), we'd end up with 110mb of old source zips hanging around.

**Comment by SeanFeldman** [comment]
@Particular/azure should this be done as a patch?

**Comment by danielmarbach** [comment]
Removed the bug label and moved it to the ice box.

**Comment by SeanFeldman** [comment]
Has already been released.
