### ISSUE TITLE
Please relax hard version of CommonServiceLocator 1.0 to allow > 1.0

### ISSUE THREAD

**Issue by CRuppert** [Particular/NServiceBus.Host.AzureCloudService#15]
Azure Hostprocess when installed conflicts with other libraries that require CSL 1.3 or higher.

Forcing the install by installing CSL 1.3, then installing hostprocess with -ignoredependencies flag with binding redirect in the app.config and NServiceBus.Hosting.Azure.HostProcess.exe.config fixes the problem and allows everything to function. 

However this prevents us from building complete nuget packages for our stuff, as attempting to install anything containing this throws this violation. **This is also a huge pain when using Nuget to do updates of any packages**, as they must be in a very specific order and allow us to miss dependencies (because of -ignoredependencies flag required for installs)

**Comment by CRuppert** [comment]
@SeanFeldman  pr #16  handles this.
 
If you can accept, we would love a build for this soon. ;)

Thanks so much!

**Comment by colin-higgins** [comment]
@SeanFeldman Should this be closed? It looks like the PR was merged into develop a while back.

**Comment by SeanFeldman** [comment]
Since it will be release with the next version, yes.
