### ISSUE TITLE
Update to Core v6

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.Host.AzureCloudService#25]
Update the host to core v6

**Comment by boblangley** [comment]
@Particular/tf-v6-launch-plat-dev Should this be part of the v6 launch? Especially since we [are moving a core interface to the host](https://github.com/Particular/NServiceBus/issues/3342).

**Comment by SeanFeldman** [comment]
@boblangley it's already taking place in #22 and #23

**Comment by yvesgoeleven** [comment]
I'll merge #22 in, I tested it on monday it was good
