### ISSUE TITLE
NServiceBus appears to take a hard reference to version 2.0.0.0 via Ionic.Zip.dll

### ISSUE THREAD

**Issue by sfarmar** [Particular/NServiceBus.Host.AzureCloudService#38]
http://stackoverflow.com/questions/37167064/nservicebus-appears-to-take-a-hard-reference-to-version-2-0-0-0-via-ionic-zip-dl

**Comment by MarcinHoppe** [comment]
This will be gone in V7 of the host. Do we want to keep this issue to consider backporting?

**Comment by yvesgoeleven** [comment]
@MarcinHoppe I don't think we can backport this, zipping in .net libs is fairly new

**Comment by MarcinHoppe** [comment]
@yvesgoeleven True. This means we can probably close this issue as fixed?

**Comment by yvesgoeleven** [comment]
done
