### ISSUE TITLE
Provide tests for the host configuration

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus.Host.AzureCloudService#48]
Currently `DynamicHostController` has no tests. i.e. properties of `HostingSettings` influencing its behavior could be changed without an error. This part of the host functionality should have a proper suite of tests. Taking into consideration that `NServiceBusRoleEntrypoint` as well as `DynamicHostController` are azure role agnostic, it should require no vm spawning.

**Comment by SeanFeldman** [comment]
@Scooletz please elaborate on what needs to be tested.

**Comment by Scooletz** [comment]
@SeanFeldman Updated the initial description.

**Comment by danielmarbach** [comment]
We are deprecating this host. I'm closing this since I do not think it is worth improving the testing situation under that light.
