### ISSUE TITLE
Azure host V6 DisplayName incorrectly displays machine name

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.Host.AzureCloudService#54]
## Who's affected

* All users using ServicePulse or the host DisplayName header value to differentiate endpoint instances of the AzureCloudService Host.

## Symptoms

The DisplayName is used by ServicePulse to differentiate instances. Using the machine name is not very helpful in Azure as the deployed machine can be changed at any time.

## Workaround

To get more meaningful display names, the following can be applied

```c#
configuration.GetSettings().Set("NServiceBus.HostInformation.DisplayName", displayName);
```

where `displayName` is a constant value meaningful for troubleshooting.

[Examples](https://groups.google.com/forum/#!topic/particularsoftware/URnuGDf27QM): 
* For Cloud Services it could be role name + role instance Id available with `RoleEnvironment`.
* For WebJobs it could be website instance Id environment variable

## Description

The endpoint name no longer shows the Role Instance Id as was intended. [This line](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/master/src/NServiceBus.Hosting.Azure/GenericHost.cs#L131) does not set the DisplayName property which is used by ServicePulse and other items to provide a user-friendly way to identify the Cloud Service instance.

To change the DisplayName in NServiceBus V5 the setting must be set by accessing the settings direclty:

`configuration.GetSettings().Set("NServiceBus.HostInformation.DisplayName", "displayName");`

In addition for NServiceBus.Host.AzureCloudService the initialization can be simplified by removing the lines ([127](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/master/src/NServiceBus.Hosting.Azure/GenericHost.cs#L127), [130](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/master/src/NServiceBus.Hosting.Azure/GenericHost.cs#L130)) relating to setting the host id since line [131](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/master/src/NServiceBus.Hosting.Azure/GenericHost.cs#L131) performs the same function:

```
                var host = SafeRoleEnvironment.CurrentRoleName;
                var instance = SafeRoleEnvironment.CurrentRoleInstanceId;
                configuration
                    .UniquelyIdentifyRunningInstance()
                    .UsingNames(instance, host);
```

Ideally an extension point would be available to allow the user to easily set a cloud service name as well as the instance id as the display name. This would allow users that deploy the same host (endpoint) to multiple cloud services to distinguish between them.

Otherwise we should update documentation to explain that by default we assume 1 endpoint == 1 cloud service and show the user how to modify the display name if they are deploying the same endpoint host to multiple cloud services.

**Comment by boblangley** [comment]
Split V6 host bug from #49 as requested

**Comment by boblangley** [comment]
This doco http://docs.particular.net/nservicebus/hosting/override-hostid mentions `$.diagnostics.hostdisplayname` as the header value that includes the display name. This is set by the setting `NServiceBus.HostInformation.DisplayName` in the work-around above.

That workaround listed above is not meant to be used verbatim, I assume we can come up with a runtime value that is appropriate instead of `"displayName"`.

**Comment by SeanFeldman** [comment]
Backwards compatibility [discussion](https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/53#discussion_r64610617)

**Comment by boblangley** [comment]
I updated the Who's Affected section with a better description.

**Comment by SeanFeldman** [comment]
[Analysis](https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/49#issuecomment-221718787) performed for Azure v7 host includes information for v6 host as well.
In Azure v6 host the `DisplayName` of `endpoint@machinename` was not helpful because machine name was changing over the time. When SP doesn't receive heartbeats for a specific endpoint instance, to troubleshoot that instance, one would have to know how to map `endpoint@machinename` to a specific role instance. Unfortunately, machinename is not easily mapping to a role instance. To resole this, either the whole cloud service would be restarted, or RDP connection to each role instance would be required to identify the required machine.

Possible solution is to set `DisplayName` to the role name + role instance id. Endpoints then would be represented in the following way: `endpoint@rolename_roleinstanceid`

**Comment by SeanFeldman** [comment]
After discussion with @boblangley and @johnsimons, conclusion is that SC and SI could be affected for the customers with already registered endpoints.

**Comment by SeanFeldman** [comment]
@Particular/azure-host-maintainers back-porting this issue requires SC/SI changes as well.
Do we provide workaround for azure host v6 and leave it as is?

**Comment by SeanFeldman** [comment]
Update: added workaround section to provide 2 possible options (for CSes and WebJobs).

**Comment by andreasohlund** [comment]
I'd say go with the workaround for now. We can always reconsider if we get users asking for this?

**Comment by johnsimons** [comment]
> I'd say go with the workaround for now. We can always reconsider if we get users asking for this?

@andreasohlund I would recommend u install SC and SP and try to use it with Azure, and then make this call

**Comment by johnsimons** [comment]
@SeanFeldman how much work would this be ?

**Comment by SeanFeldman** [comment]
On the azure host - very little coding, a lot of testing in conjunction with SC/SP/SI.
There would be work required on the SC/SP side (not sure about SI).

**Comment by andreasohlund** [comment]
>I would recommend u install SC and SP and try to use it with Azure, and then make this call

Not arguing that running SC on Azure is non optimal. But is this the only problem? Should we take one step back and list all the issues that we have relating to running SC on Azure?

**Comment by johnsimons** [comment]
@andreasohlund IMHO this is the biggest pain point we currently have in ServicePulse, the UI is just an ocean of decommissioned instances.
Yes there are other issues, but I would definetly start with this one
