### ISSUE TITLE
Cannot override endpoint name with a value determined at runtime

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Host.AzureCloudService#57]
When hosting an endpoint with Cloud Services, the [documented options](http://docs.particular.net/nservicebus/endpoints/specify-endpoint-name) to specify a custom endpoint name are:

1. Namespace convention
1. `EndpointName[]` attribute
1. Installation parameter
1. Command line parameter
1. ~~Input queue override~~ doesn't seem to affect everything related to the endpoint name

When endpoint name needs to be determined at the runtime, none of these options work for azure host.
With self hosted endpoints, endpoint name can be easily controlled when `EndpointConfiguration` is created. With hosts, `IConfigureThisEndpoint` receives an already constructed `endpointConfiguration` object which doesn't allow endpoint name modifications.

**Comment by AndreasESchneider** [comment]
@SeanFeldman setting the endpoint name dynamically is helpful for us to isolate workstations from each other while using the same AzureServiceBus transport configuration in the cloud for dev and test. We might see that messages are picked up and processes from another running dev or test workstation which is unwanted for this use-case.

There might be another (hypothetic) use case for dynamically created endpoint names if you need to isolate endpoints for different customers as alternative to use different transport configurations.

**Comment by yvesgoeleven** [comment]
Perhaps add a property on IConfigureThisEndpoint that users can/must implement

**Comment by SeanFeldman** [comment]
@danielmarbach had a spike related to this issue (issue https://github.com/Particular/NServiceBus/issues/2477)

**Comment by AndreasESchneider** [comment]
@yvesgoeleven maybe a virtual call for the endpoint name which could be overwritten in the class implementing IConfigureThisEndpoint might be helpfull?

**Comment by andreasohlund** [comment]
Me and @danielmarbach talked about this and the proposal is to introduce a host specific


`config.DefineEndpointName("someName")` that would set the name in the settings dictionary

Ie:

```
MyConfig: IConfigureThisEndpoint
{
     Init(EndpointConfiguration config)
{ 
   config.DefineEndpointName("customEndpointName");
}
}

```

**Comment by SeanFeldman** [comment]
That works. Should it be consistent between Azure host and the regular host or we don't care @andreasohlund ?

**Comment by andreasohlund** [comment]
The idea was to make it consistent unless there is some api that makes more sense for Azure?

**Comment by danielmarbach** [comment]
See 

https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/58
https://github.com/Particular/NServiceBus.Host/pull/92

**Comment by mikeminutillo** [comment]
@yvesgoeleven @SeanFeldman does @danielmarbach's fix address this issue? Can this be closed?

**Comment by yvesgoeleven** [comment]
@mikeminutillo yes indeed, closing
