### ISSUE TITLE
DefineEndpointName System.InvalidCastException

### ISSUE THREAD

**Issue by peto268** [Particular/NServiceBus.Host.AzureCloudService#60]
When trying to set my endpoint name using:
`endpointConfiguration.DefineEndpointName("Endpoint");`
I get an: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'NServiceBus.Routing.EndpointName'.

Maybe the DefineEndpointName extension should look something like this:
`configuration.GetSettings().Set("NServiceBus.Routing.EndpointName", new EndpointName(endpointName));`

**Comment by SeanFeldman** [comment]
@peto268 what version of NServiceBus and AzureCloudService are you using? Looks like versions are out of sync. Extension method in the latest beta is using a `string` since core is switched to use a `string` as well.

**Comment by peto268** [comment]
NServiceBus is version 6.0.0-beta0004
NServiceBus.Hosting.Azure" is version 7.0.0-beta0003

**Comment by SeanFeldman** [comment]
New beta packages were published.
Could you please upgrade and confirm if the issue is resolved for you?

**Comment by peto268** [comment]
It's working now, thanks.
