### ISSUE TITLE
Incorrect log source

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Host.AzureCloudService#66]
Incorrect log source is used in the following classes:
1. [`DynamicHostMonitor`](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/release-7.0.0/src/NServiceBus.Hosting.Azure/DynamicHost/DynamicHostMonitor.cs#L15)
1. [`DynamicEndpointProvisioner`](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/release-7.0.0/src/NServiceBus.Hosting.Azure/DynamicHost/DynamicEndpointProvisioner.cs#L8)

Both v6 and v7 of the ACS host are affected.

**Comment by Scooletz** [comment]
We're going to fix it only on the develop of the latest version.
