### ISSUE TITLE
V6 Multi-host cloud service is not restarted when a critical error is raised

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Host.AzureCloudService#67]
## Who's affected

Any Azure customers using Cloud Services (CS) to multi-host endpoints

## Symptoms

Endpoints encounter critical error, shutdown, but the multi-hosting CS doesn't restart.

## Workaround

Restart CS manually to restart all endpoint.

## Details

`DynamicEndpointRunner` does not get the `RecycleRoleOnError` flag set, which will never allow it to [request CS to restart](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/218bdff026d728b9f74a6955f1fd683dbe471314/src/NServiceBus.Hosting.Azure/DynamicHost/DynamicEndpointRunner.cs#L57) upon endpoints critical errors.

**Comment by SeanFeldman** [comment]
related to #68

**Comment by yvesgoeleven** [comment]
I think we were blind when looking at this, the property is set https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/support-6.2/src/NServiceBus.Hosting.Azure/DynamicHost/DynamicHostController.cs#L50
