### ISSUE TITLE
V7 Multi-host cloud service is not restarted when a critical error is raised

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Host.AzureCloudService#68]
## Who's affected

Any Azure customers using Cloud Services (CS) to multi-host endpoints

## Symptoms

Endpoints encounter critical error, shutdown, but the multi-hosting CS doesn't restart.

## Workaround

Restart CS manually to restart all endpoint.

## Details

`DynamicEndpointRunner` does not get the `RecycleRoleOnError` flag set, which will never allow it to [request CS to restart](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/67def5903e1d3e101a46f2b1651ed7808777b314/src/NServiceBus.Hosting.Azure/DynamicHost/DynamicEndpointRunner.cs#L55) upon endpoints critical errors.

**Comment by SeanFeldman** [comment]
related to #67

**Comment by yvesgoeleven** [comment]
Closing this one, it works fine in V7 https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/develop/src/NServiceBus.Hosting.Azure/DynamicHost/DynamicHostController.cs#L32
