### ISSUE TITLE
ZipFile.ExtractToDirectory does not allow overwrite

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Host.AzureCloudService#69]
## Who's affected

- Anyone using Azure Cloud Services and using [shared hosting](https://docs.particular.net/nservicebus/hosting/cloud-services-host/shared-hosting)

## Symptoms

Shared-hosted endpoints fail to update due to file overwrite failure when extracted from zip files.

## Original issue

The following line would throw when there is already are existing files, causing the endpoint to not be hosted.

https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/develop/src/NServiceBus.Hosting.Azure/DynamicHost/EndpointToHost.cs#L39

**Comment by Scooletz** [comment]
Should this issue be closed then @yvesgoeleven  as #70 is merged?

**Comment by yvesgoeleven** [comment]
@Scooletz I think we still need to release this, right @SeanFeldman ?

**Comment by SeanFeldman** [comment]
Correct. Needs proper description (who's affected, etc) and a milstone. And then can be released.

**Comment by Scooletz** [comment]
@yvesgoeleven Could you provide a better description for it?
