### ISSUE TITLE
Shared host is not discovered during assembly scanning

### ISSUE THREAD

**Issue by onesadjam** [Particular/NServiceBus.Host.AzureCloudService#84]
The documentation for shared hosting indicates the worker role need only provide a public class that implement IConfigureThisHost:

https://docs.particular.net/nservicebus/hosting/cloud-services-host/shared-hosting

However, in practice the assembly scanner is only looking for classes that implement IConfigureThisEndpoint (NServiceBus.Host.AzureCloudService/src/NServiceBus.Hosting.Azure/RoleHost/Entrypoint.cs:102).  

The shared hosting sample code demonstrates implementing both interfaces, but this should not be necessary.  To correct this issue, the EntryPoint.cs should be modified to scan for both types that implement IConfigureThisEndpoint as well as IConfigureThisHost.

```
            return scanResult.Types.Where(
                    t => 
                         (
                              typeof(IConfigureThisEndpoint).IsAssignableFrom(t)
                              || typeof(IConfigureThisHost).IsAssignableFrom(t)
                         )
                         && t != typeof(IConfigureThisEndpoint)
                         && t != typeof(IConfigureThisHost)
                         && !t.IsAbstract);
```

**Comment by boblangley** [comment]
@onesadjam I am looking into this. I will get back to you about your PR shortly.

**Comment by SeanFeldman** [comment]
Blocked by https://github.com/Particular/NServiceBus/issues/4769

**Comment by SeanFeldman** [comment]
Pending core PR: https://github.com/Particular/NServiceBus/pull/4784

**Comment by SeanFeldman** [comment]
Core 6.3.4 [is out](https://github.com/Particular/NServiceBus/releases/tag/6.3.4). Not blocked anymore.

**Comment by SeanFeldman** [comment]
Hotfixes 7.0.4 and 7.1.3 where [released](https://www.nuget.org/packages/NServiceBus.Hosting.Azure) and announced. Thank you @onesadjam
