### ISSUE TITLE
Dynamic host runs as an MSMQ endpoint

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Host.AzureCloudService#89]
Currently, Dynamic host is running as a send-only endpoint with the default transport, which is MSMQ.

Should dynamic host be an endpoint at all? 
We shouldn't rely on MSMQ availability on the worker roles and endpoints should be hosted.
In case send-only hosting endpoint was sending any messages (by accessing `IMessageSession` via `IWantToRunWhenEndpointStartsAndStops`), functionality should be moved out into appropriate endpoint.

Related to #84 

Connects to https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/100

**Comment by yvesgoeleven** [comment]
dynamic host leverages part of the core, to do assembly scanning, uses the configuration model etc.. this causes defaults to apply, hence msmq is on. If we want to prevent these defaults, we'd need to rip the core out and include these capabilities separatly. Is it worth the effort given that SF now exists?

**Comment by SeanFeldman** [comment]
> we'd need to rip the core out

yes

>  include these capabilities separatly

Not so sure about this part. Shouldn't multi-host be used as a host and not as an send-only endpoint? This is why we could introduce it as a new major, were we can have such a breaking behavior.

> it worth the effort given that SF now exists?

Good question. Right now we're relying on an undocumented feature - MSMQ installed by default. If that changes, any multi-host is dead in the water. Not to mention that by running an endpoint for the host, we are wasting resources that would go towards actual endpoints.

**Comment by boblangley** [comment]
I do not think the host should also act as an NServiceBus endpoint if it has been configured to run as a dynamic host, and I don't see any reason to abandon the dynamic host for SF just yet.

My suggestion would be to limit the change to just the following:

- Add a third check to [ValidateEndpoints](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/develop/src/NServiceBus.Hosting.Azure.HostProcess/Program.cs#L86) to confirm that the single found "endpoint" only implements `IConfigureThisEndpoint` or `IConfigureThisHost`, not both. If it implements both then throw with a friendly message telling users to do one or the other.

- Remove the NServiceBus endpoint from the [DynamicHostController](https://github.com/Particular/NServiceBus.Host.AzureCloudService/blob/develop/src/NServiceBus.Hosting.Azure/DynamicHost/DynamicHostController.cs#L14-L20).

- Update the doco accordingly.

**Comment by yvesgoeleven** [comment]
Agreed, this should not run as an endpoint

**Comment by danielmarbach** [comment]
Sent in https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/104 to implement what @boblangley proposed
