### ISSUE TITLE
Figure out why exe requires net35 when exe.config file is added

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Host.AzureCloudService#98]
https://github.com/Particular/docs.particular.net/issues/2840#event-1126392732

**Comment by yvesgoeleven** [comment]
Tried to reproduce this on new azure vm, windows server 2016 datacenter with no net35 installed... but the endpoint just worked without prompting

**Comment by yvesgoeleven** [comment]
@SteveWinward what os were you using when you saw this issue?

**Comment by SteveWinward** [comment]
@yvesgoeleven I'm running the sample on a Windows 10 vm.  Version 1703, Build 15063.296.

**Comment by yvesgoeleven** [comment]
@stevewinward can you try on another version (ideally clean image) of windows 10?

**Comment by SteveWinward** [comment]
So I just created a brand new Windows 10 Enterprise N vm in Azure.  When I copy over the bin files into the Azure vm and run the host process I do not get the .NET 3.5 install prompt.  

There must be something different between my personal dev machine and the fresh Windows 10 image in Azure.  Thanks for your help with looking into this.

**Comment by yvesgoeleven** [comment]
@SteveWinward sounds like a machine specific issue then. I'm going to close this issue. In case you find a relationship specific to the hostprocess feel free to reopen it.
